#pragma once

#define MQTT_TOPIC_ROOT_CONTROLLER "robohand/" CONFIG_UUID

#define MQTT_TOPIC_MONITORING MQTT_TOPIC_ROOT_CONTROLLER "/monitoring"
#define MQTT_TOPIC_CONTROL MQTT_TOPIC_ROOT_CONTROLLER "/control"

#define MQTT_TOPIC_MONITORING_IMU MQTT_TOPIC_MONITORING  "/imu"
#define MQTT_TOPIC_MONITORING_STRAIN_GAUGE MQTT_TOPIC_MONITORING "/strain_gauge"
#define MQTT_TOPIC_MONITORING_SERVO MQTT_TOPIC_MONITORING "/servo"
#define MQTT_TOPIC_MONITORING_POTENTIOMETER MQTT_TOPIC_MONITORING "/potentiometer"