#pragma once

#define MQTT_TOPIC_ROOT_CONTROLLER "robohand/" CONFIG_UUID

#define MQTT_TOPIC_MONITORING MQTT_TOPIC_ROOT_CONTROLLER "/monitoring"
#define MQTT_TOPIC_COMMANDS MQTT_TOPIC_ROOT_CONTROLLER "/commands"
#define MQTT_TOPIC_NOTIFICATIONS MQTT_TOPIC_ROOT_CONTROLLER "/notifications"

#define MQTT_TOPIC_MONITORING_IMU MQTT_TOPIC_MONITORING  "/imu"
#define MQTT_TOPIC_MONITORING_STRAIN_GAUGE MQTT_TOPIC_MONITORING "/strain_gauge"
#define MQTT_TOPIC_MONITORING_SERVO MQTT_TOPIC_MONITORING "/servo"
#define MQTT_TOPIC_MONITORING_POTENTIOMETER MQTT_TOPIC_MONITORING "/potentiometer"

#define MQTT_TOPIC_MONITORING_IMU_RAW_DATA MQTT_TOPIC_MONITORING_IMU "/raw-data"
#define MQTT_TOPIC_MONITORING_IMU_PROCESSED_DATA MQTT_TOPIC_MONITORING_IMU "/processed-data"

#define MQTT_TOPIC_MONITORING_STRAIN_GAUGE_PRESSURE_AT_FINGERTIPS MQTT_TOPIC_MONITORING_STRAIN_GAUGE "/pressure-at-fingertips"

#define MQTT_TOPIC_MONITORING_SERVO_INFO MQTT_TOPIC_MONITORING_SERVO "/info"

#define MQTT_TOPIC_MONITORING_POTENTIOMETER_ANGLE_MEASUREMENT MQTT_TOPIC_MONITORING_POTENTIOMETER "angle-measurements"

#define MQTT_TOPIC_COMMANDS_SERVO_GO_TO_ANGLE MQTT_TOPIC_COMMANDS "/servo-go-to-angle"
#define MQTT_TOPIC_COMMANDS_SERVO_LOCK MQTT_TOPIC_COMMANDS "/servo-lock"
#define MQTT_TOPIC_COMMANDS_SERVO_UNLOCK MQTT_TOPIC_COMMANDS "/servo-unlock"
#define MQTT_TOPIC_COMMANDS_SERVO_SMOOTHLY_MOVE MQTT_TOPIC_COMMANDS "/servo-smoothly-move"
#define MQTT_TOPIC_COMMANDS_MOVE_TARGET_PRESSURE MQTT_TOPIC_COMMANDS "/move-target-pressure"
#define MQTT_TOPIC_COMMANDS_HOLD_GESTURE MQTT_TOPIC_COMMANDS "/hold-gesture"